# Generated by Django 5.2.9 on 2025-12-13 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Aluno')),
                ('course_name', models.CharField(max_length=255, verbose_name='Nome do Curso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_valid', models.BooleanField(default=True)),
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-created_at'],
            },
        ),
    ]
