# Generated by Django 5.2.9 on 2025-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='instructor_name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Nome do Instrutor'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='instructor_role',
            field=models.CharField(default='Coordenador (a)', max_length=255, verbose_name='Cargo'),
        ),
    ]
